name: Package for distribution

on: workflow_dispatch

env:
  CSC_IDENTITY_AUTO_DISCOVERY: false

jobs:
  package:
    strategy:
      fail-fast: false
      matrix:
        os: [windows-latest, ubuntu-18.04, macos-latest]

        # OS-specific commands/variables
        include:
          - os: ubuntu-18.04
            cmd_package: npm run package-linux
            out_filename: Bob-linux
          - os: windows-latest
            cmd_package: npm run package-win
            out_filename: Bob-windows
          - os: macos-latest
            cmd_package: npm run package-mac
            out_filename: Bob-macos-intel

    runs-on: ${{matrix.os}}

    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Use Node.js 16.x
        uses: actions/setup-node@v1
        with:
          node-version: 16.x

      - name: Install dependencies (linux only)
        if: matrix.os == 'ubuntu-18.04'
        run: sudo apt update && sudo apt install libudev-dev libusb-1.0-0-dev -y

      - name: Install npm packages
        run: npm i

      - name: Install dmg-license (macos only)
        if: startsWith(matrix.os, 'macos')
        run: npm i dmg-license --no-save

      - name: Generate Executable
        run: ${{ matrix.cmd_package }}

      - name: Store artifacts
        uses: actions/upload-artifact@v2
        with:
          name: ${{ matrix.out_filename }}
          path: |
            release/*.AppImage
            release/*.msi
            release/*.dmg
